### ISSUE TITLE
部分频道的视频无法下载(例如纪录片频道)

### ISSUE THREAD

**Issue by zby1234** [larvata/abema-hls-dl#3]
使用的是日本IP段的VPS下载，部分频道可以顺利下载，但是部分频道无法下载(未测试所有频道)，例如纪录片频道，提示如下：
root@xyz:~/abema# nodejs . -s -d 150 -c documentary
{ channelId: 'documentary',
  recordDuration: '150',
  recordStart: 2017-05-20T14:55:48.936Z,
  saveCacheFile: true }
Begin a schedule for recording.
ad:  {
  "duration": 5,
  "uri": "https://abematv.akamaized.net/tsda/documentary/9BMXQH4XXSUKks/3125/44.                                                                                                 ts",
  "timeline": 1
}
ad:  {
  "duration": 5,
  "uri": "https://abematv.akamaized.net/tsda/documentary/9BMXQH4XXSUKks/3125/45.                                                                                                 ts",
  "timeline": 1
}
ad:  {
  "duration": 5,
  "uri": "https://abematv.akamaized.net/tsda/documentary/9BMXQH4XXSUKks/3125/46.                                                                                                 ts",
  "timeline": 1
}
ad:  {
  "duration": 5,
  "uri": "https://abematv.akamaized.net/tsda/documentary/9BMXQH4XXSUKks/3125/47.                                                                                                 ts",
  "timeline": 1
}
ad:  {
  "duration": 5,
  "uri": "https://abematv.akamaized.net/tsda/documentary/9BMXQH4XXSUKks/3125/48.                                                                                                 ts",
  "timeline": 1
}
...
上述显示的部分片段下载后显示如下 http://t.cn/Ra3lfAm

**Comment by larvata** [comment]
纪录片频道其他番组没有发现这个问题  
目前这个程序是模拟的设备是网页端 估计乃团的纪录片只能在移动设备上播放 你在录制的时候是否留意过网页版是否能够观看 

> Q.特定の番組のみ「視聴できないコンテンツ」と表示される
> AbemaTVでは、コンテンツの著作権保護を強化するための仕組みを導入しております。
これにより、一部の番組が特定のデバイスで視聴できない場合があります。
「視聴できないコンテンツ」と表示された場合は、デバイスを変えて視聴をお試しください。

由于限制设备的番组很少 目前我没有实现其他设备的打算

**Comment by zby1234** [comment]
乃团的纪录片当时在网页端可以收看，用的是日本地区的代理配合您写的改状态到status: 200的插件。
后来在尝试录制某些动画的时候也会出现这个问题(网页端同样可以观看)，大概确实是版权的问题？

**Comment by larvata** [comment]
稍微看了下 版权保护的视频使用了mpeg dash
这个程序目前只实现了hls 
无法下载应该是这个原因 和设备模拟无关

如果有时间 可能会实现一下

**Comment by pinkdd2017** [comment]
软件无法使用了，忘博主修复
node . --list
D:\abema-hls-dl\index.js:3
const {createUserDevice} = require('./lib/utils');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
